### ISSUE TITLE
H-atom addition not working

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/BioIn#10]
**software version- PRiNS_D_V_2_0_2_windows 
machine- PIPL01**
Structure patcher not working. PDBs used - 4TSY, 2HJ6. In the last exe version it did work for these compounds.

![4TSYhadditionerror](https://user-images.githubusercontent.com/111036161/186593734-b467c8ae-8821-4660-9ca5-f6b0f3e77f79.JPG)
![2HJ6hadditionerror](https://user-images.githubusercontent.com/111036161/186593827-e8b2a954-c566-4742-b333-b51b4360f472.JPG)

**Comment by SumedhaBhosale** [comment]
Structure Patcher not working. 

PDB ID - 7MEQ
Linux OS 

![Bio_StructurePatcher](https://user-images.githubusercontent.com/105902516/186595856-c4a4f913-938d-4875-afa0-d53c0f171ad9.png)

**Comment by mdaakhan** [comment]
Check With Lobelia working if Reappears Issue can be reopened

**Comment by LobeliaG** [comment]
PIPL01
TEST_V2_3- windows
PDB used- 6WKQ
Structure patcher not working.
![image](https://user-images.githubusercontent.com/111036161/187153135-a93b3939-43b4-464b-844f-0349a3c41d7b.png)
