### ISSUE TITLE
PDB specific issue- error in loop refinement 

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/BioIn#11]
PDB ID- 7CYN
software -PRiNS_D_V_2_0_2_windows

Working fine till missing residue modelling. But on clicking refine model, gives no results.

![7cynalign](https://user-images.githubusercontent.com/111036161/186636088-a7680e7e-cdcd-4a61-9700-bfcf81a6bcbc.JPG)
![7CYNlooperror](https://user-images.githubusercontent.com/111036161/186636095-699f8346-8160-401f-9b8c-e196b1a89a61.JPG)

**Comment by mdaakhan** [comment]
There is an upper cap of 255 elements in loop refinement. Added alert message into it
Commit ID: V2: f4219db
V1: a2eca0f
@LobeliaG Please include this in Mannual
