### ISSUE TITLE
SW got crashed after loading earlier saved directory and clicked on 'Structure patcher'

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/BioIn#23]
Hi,

One project saved earlier which reloaded using 'Browse Project Directory' option and all the data from reports to Structure Editor was getting displayed. After I clicked on Export (Structure Patcher)', sw got crashed abruptly. 
PDB ID used was : 1XKK. Project was saved just minutes ago reloading. Please check !

**Comment by SumedhaBhosale** [comment]
Screenshot for the same is unavailable at the moment ! I hope @prescienceit you can re-create this scenario.

**Comment by mdaakhan** [comment]
Already Solved in the previous version
