### ISSUE TITLE
BioIn- Homology Modeling - 'Fetch' is not working

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/BioIn#3]
In the homology modelling, At select template 'Fetch' is not getting any results.
![HomologyModeling](https://user-images.githubusercontent.com/105902516/170685502-f8b8025a-66ba-4358-8710-9ede48478a2c.png)

**Comment by chandkc** [comment]
1. The API server can be unreachable, provide an info message in UI.
2. Wait time 60s, Info message 'its taking time to Fetch the data'. Please wait.
