### ISSUE TITLE
Visualizer - Not Showing in Basic Homology Modelling after Build model

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/BioIn#30]
Hi,

Windows machine
Hackathon exe shared on 28 Sep

Sequence - HVQNLSQVEQDGRTGHGLRRSSKFCLKEHKALKTLGIIMGTFTLCWLPFFIVNIVHVIQDNLIRKEVYILLNWIGYVNSGFNPLIYCRSPDFRIAFQELLCLRRSSLKAYGNGYSSNGNTGEQSGYHVEQEKENKLLCEDLPGTEDFVGHQGTVPSDNIDSQGRNCSTNDSLL

Template selected - 3sn6 

At Build Model

![BioIn_VisualizerNotworking](https://user-images.githubusercontent.com/105902516/192743028-ea4f1b0b-cd94-484f-b802-7e16fa01cbab.jpg)

**Comment by SumedhaBhosale** [comment]
This happens only in case where we select one template.

**Comment by mdaakhan** [comment]
Already Solved in the previous version
