### ISSUE TITLE
Unable to add hydrogen atoms

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/BioIn#38]
**PRinS_V_2_0_0_Windows**
**OS- Windows**

Add missing side chain/hydrogen atoms is not working for PDB ID **_1XKK_**. But it is working for other PDB IDs **_1G2O, 1H2C_**.
Why is it not working for 1XKK? 

![BioIn_1](https://user-images.githubusercontent.com/117424735/206110775-da3a750e-1cba-4dc5-ad8d-b4826fff5443.png)
![BioIn_2](https://user-images.githubusercontent.com/117424735/206110786-db716fcf-b26b-4dce-a219-dbd810533ff3.png)

**Comment by mdaakhan** [comment]
Fixed in Bundel V_2_1_0
