### ISSUE TITLE
Software is getting crashed!

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/BioIn#42]
**Version** - PRinS3_V_2_1_0_Ubuntu_2020_64x
**OS** - Linux
**Machine** - PIPL03

The software keeps getting crashed as soon as the PDB ID is fetched.

[Screencast from 21-03-23 02 01 40 PM IST.webm](https://user-images.githubusercontent.com/117424735/226557606-155b167d-d330-4f79-8793-7d9f4977b1e3.webm)

**Comment by mdaakhan** [comment]
Already Solved in the previous version
