### ISSUE TITLE
Protein refinement issues (zn ion)

### ISSUE THREAD

**Issue by MahimaKori** [chandkc/BioIn#43]
**Version** - PRinS3_V_2_1_0_Ubuntu_2020_64x
**OS** - Linux
**Machine** - PIPL03
**Input pdb id** - 7WQL

1. The ions are not displayed in visualizer.
2. Unable to do model refinement step if the zn ion is kept with the protein.
3. Unable to add missing side chain/Hydrogen atoms if the zn ion is kept with the protein. It shows **_There is a mistake in your chain, or it includes nonstandard residue names_** in the log

![bioin_1](https://github.com/chandkc/BioIn/assets/117424735/5279209f-a3a8-4c07-b4cc-0731da85e173)
![bioin_2](https://github.com/chandkc/BioIn/assets/117424735/a16b093f-96d1-4c77-a7e6-dd797405120a)

**Comment by mdaakhan** [comment]
Already Solved in the previous version
