### ISSUE TITLE
BioIn - SW window got freeze after Generate Alignment  

### ISSUE THREAD

**Issue by SumedhaBhosale** [chandkc/BioIn#5]
Hi,

At the time of missing residue addition using 'Generate Alignment', software window gets freeze.

System used - ubuntu 20
Version 2 - exe shared on 10 Aug
PDB ID - 1XKK

![BioIn_Sw_Freeze](https://user-images.githubusercontent.com/105902516/185563164-d853f087-0ade-4083-a6c8-a7ed74eaa799.png)

**Comment by mdaakhan** [comment]
Its in thread please check in new exe

**Comment by SumedhaBhosale** [comment]
Checked in new window exe dated 19 Aug. No freezing of software observed !

**Comment by mdaakhan** [comment]
Temporary Closing of this issue
