### ISSUE TITLE
PDB specific Error in Loop refinement, H addition 

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/BioIn#7]
**PDB ID- 4RET**, software- latest windows version, machine- PIPL01
Up until missing residue modelling its working. Then loop refinement or H addition does not work anymore.
![H addition error](https://user-images.githubusercontent.com/111036161/186094675-2e620ec5-26c7-4b24-a988-61e9a13153a3.JPG)
![loop refinement error](https://user-images.githubusercontent.com/111036161/186094690-d5b58baa-b904-4a9a-a568-86f74c5ce642.JPG)

**Comment by mdaakhan** [comment]
TERMINAL RESIDUE RENUMBER BIOIN ADDITION 
V1: 0a2069c7dbdf04484a0a9f2149facf661f4d5138
v2: 8b68add469b51f6b9ea36b6a734e0566f56546a0
