### ISSUE TITLE
Visualizer not updating in homology modelling

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/BioIn#8]
PDB- 2HJ6, machine- PIPL01, software- windows latest version 
The visualizer not updating with the selection of different homology models that are generated.

![noupdate](https://user-images.githubusercontent.com/111036161/186106456-a77a1d2f-05ca-40f6-92cd-f01f0e9b1be9.JPG)
![noupdate1](https://user-images.githubusercontent.com/111036161/186106465-3ec659f5-a2d3-4a8d-8c0b-628cd216e244.JPG)
![noupdate2](https://user-images.githubusercontent.com/111036161/186106471-321b4621-a472-42a7-b1a7-4de7c3f2c99f.JPG)

**Comment by mdaakhan** [comment]
Visualizer is updating, you can see the name by hover on the visulaizer
