### ISSUE TITLE
Inaccurate information on pop-up

### ISSUE THREAD

**Issue by LobeliaG** [chandkc/BioIn#9]
**software version- PRiNS_D_V_2_0_2_windows** 
T**ab- Structure modelling-search template** 
If there is anything wrong with the input, this pop-up comes up. However this should be UniProt ID, not PDB ID. Although, here my input ID was correct but I had put an extra space after the ID.

![space_after_uniprot](https://user-images.githubusercontent.com/111036161/186576557-7c7c054c-cb3a-4404-9f5a-390490b512f5.JPG)

**Comment by mdaakhan** [comment]
fixed V2:
Commit ID: f829e14
